package model;
// Generated 17.May.2018 11:22:14 by Hibernate Tools 4.3.1



/**
 * Musteri generated by hbm2java
 */
public class Musteri  implements java.io.Serializable {


     private int musteriid;
     private String musteriad;
     private String musterisoyad;
     private String adres;
     private long telno;

    public Musteri() {
    }

    public Musteri(int musteriid, String musteriad, String musterisoyad, String adres, long telno) {
       this.musteriid = musteriid;
       this.musteriad = musteriad;
       this.musterisoyad = musterisoyad;
       this.adres = adres;
       this.telno = telno;
    }
   
    public int getMusteriid() {
        return this.musteriid;
    }
    
    public void setMusteriid(int musteriid) {
        this.musteriid = musteriid;
    }
    public String getMusteriad() {
        return this.musteriad;
    }
    
    public void setMusteriad(String musteriad) {
        this.musteriad = musteriad;
    }
    public String getMusterisoyad() {
        return this.musterisoyad;
    }
    
    public void setMusterisoyad(String musterisoyad) {
        this.musterisoyad = musterisoyad;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public long getTelno() {
        return this.telno;
    }
    
    public void setTelno(long telno) {
        this.telno = telno;
    }




}


